type: object
x-stoplight:
  id: sbik5xsixage8
description: |-
  Seapim product that groups one or more API proxies.

  A record is uniquely identified by seapimOrg + productName combined
required:
  - id
  - seapimOrg
  - productName
  - createdAt
  - updatedAt
  - consumers
  - productProxies
properties:
  id:
    $ref: ../models/Id.yaml
    x-stoplight:
      id: e9qhsan3v9fxg
    description: Database identifier
  seapimOrg:
    $ref: ./SEAPIM Org.yaml
    x-stoplight:
      id: 5pem430h3i61b
    description: SEAPIM platform organisation name
  productName:
    type: string
    x-stoplight:
      id: vaqgmxty24lov
    example: Product-SE API Managment
    description: Product name
  callRate:
    type: integer
    x-stoplight:
      id: 05e8s9lvsuq1t
    description: 'Allocated maximum number of API calls allowed per minute, converted from actual SEAPIM quota configuation which may be defined using a different time unit'
    example: 600
  quota:
    type: integer
    x-stoplight:
      id: 5fmnxlseibo0q
    description: 'SEAPIM quota number, first part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 1000
  quotaInterval:
    type: integer
    x-stoplight:
      id: ph5d64bhx20wi
    description: 'SEAPIM quota interval, second part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
    example: 2
  quotaTimeunit:
    $ref: ./Quota Time Unit.yaml
    x-stoplight:
      id: m0uts2t5rp3fh
    description: 'SEAPIM quota time unit, third part of a triplet: quota number per (interval * time unit). For example 1000 per 2 * hour'
  scopes:
    type: array
    x-stoplight:
      id: wk3wejb8ufq9b
    description: 'List of API scopes which grant conditional access to specified API, using partial matching of operations by a string in the endpoint path'
    items:
      x-stoplight:
        id: co0vuwdtuzszj
      type: string
      example: 'urn:API-Metadata-V2:*:read, urn:API-Metadata-V2:apis:write"'
  createdAt:
    $ref: ../models/CreatedAt.yaml
    description: The time this record was created
    x-stoplight:
      id: nqhy833h1zuyj
  updatedAt:
    $ref: ../models/UpdatedAt.yaml
    description: The time this record was last updated
    x-stoplight:
      id: gk0huz8gcysna
  consumers:
    type: array
    x-stoplight:
      id: 4uyywamfx7yr3
    description: List of application consumers with a subscription that refers to this product
    items:
      $ref: ./Consumer.yaml
      x-stoplight:
        id: hyh2dy96p2l8m
  productProxies:
    type: array
    x-stoplight:
      id: gk84r7b1fucvf
    description: List of API proxies included in this product
    items:
      $ref: ./Product Proxy.yaml
      x-stoplight:
        id: n6qfizyl6xn8t
title: ''
